from pwny.types import *

BUILTIN_BASE = 1
TAB_BASE = 1

API_CALL = 1
API_TYPE = 1
API_CALL_STATIC = 10000
API_CALL_DYNAMIC = 40000

TLV_TYPE_PLATFORM = tlv_custom_type(TLV_TYPE_STRING, 1)
TLV_TYPE_VERSION = tlv_custom_type(TLV_TYPE_STRING, 2)
TLV_TYPE_ARCH = tlv_custom_type(TLV_TYPE_STRING, 3)
TLV_TYPE_MACHINE = tlv_custom_type(TLV_TYPE_STRING, 4)
TLV_TYPE_VENDOR = tlv_custom_type(TLV_TYPE_STRING, 5)

TLV_TYPE_PID_STATE = tlv_custom_type(TLV_TYPE_PID, 1)
TLV_TYPE_PID_CPU = tlv_custom_type(TLV_TYPE_PID, 2)

API_QUIT = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL)
API_ADD_NODE = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 1)
API_DEL_NODE = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 2)
API_ADD_TAB_DISK = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 3)
API_ADD_TAB_BUFFER = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 4)
API_DEL_TAB = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 5)
API_MIGRATE = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 6)
API_PULL = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 7)
API_PUSH = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 8)
API_SYSINFO = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 9)
API_PROCESS_LIST = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 10)
API_PROCESS_KILL = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 11)
API_GET_PID = tlv_custom_tag(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 12)
