from pwny.types import tlv_custom

BUILTIN_BASE = 1

API_CALL = 1
API_CALL_STATIC = 10000
API_CALL_DYNAMIC = 40000

API_QUIT = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL)
API_ADD_NODE = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 1)
API_DEL_NODE = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 2)
API_ADD_TAB_DISK = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 3)
API_ADD_TAB_BUFFER = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 4)
API_DEL_TAB = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 5)
API_MIGRATE = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 6)
API_PULL = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 7)
API_PUSH = tlv_custom(API_CALL_STATIC, BUILTIN_BASE, API_CALL + 8)
