injector:
	@echo "[Building injector]"
	@cd ../deps/build/; \
	git clone https://github.com/kubo/injector; \
	cd injector/src/$(PLATFORM); \
	make $(shell $(MAKE_TOOLCHAIN_FILE)); \
	cp libinjector.a ../../../; \
	cp ../../include/injector.h ../../../; \
	cp injector_internal.h ../../../
	@echo "[Done building injector]"
