injector:
	@echo "[Building injector]"
	@cd ../deps/$(PLATFORM)/$(ARCH); \
	git clone https://github.com/kubo/injector; \
	cd injector/src/$(PLATFORM); \
	make $(shell sh ../../../../../../toolchain/make/$(PLATFORM)/$(ARCH).sh); \
	cp libinjector.a ../../../; \
	cp ../../include/injector.h ../../../
	@echo "[Done building injector]"