libeio:
	@echo "[Building libeio]"
	@cd ../deps/$(PLATFORM)/$(ARCH); \
	git clone https://github.com/libev-cn/libeio; \
	cd libeio; \
	sh autogen.sh; ./configure; \
	make $(shell ../toolchain/make/$(PLATFORM)_$(ARCH).sh); \
	cp .libs/libeio.a ../; \
	cp eio.h ../
	@echo "[Done building libeio]"