libpawn:
	@echo "[Building libpawn]"
	@cd ../deps/$(PLATFORM)/$(ARCH); \
	git clone https://github.com/entysec/libpawn; \
	cd libpawn; \
	cmake -DARCH=$(ARCH) -DCMAKE_TOOLCHAIN_FILE=../../../../cmake/$(PLATFORM)_$(ARCH).cmake -DDEBUG=ON -B build; \
	cmake --build build; \
	cp build/libpawn.a ../; \
	cp include/pawn.h ../
	@echo "[Done building libpawn]"