libev:
	@echo "[Building libev]"
	@cd ../deps/$(PLATFORM)/$(ARCH); \
	git clone https://github.com/libev-cn/libev; \
	cd libev; \
	sh autogen.sh; ./configure; \
	make $(shell ../toolchain/make/$(PLATFORM)_$(ARCH).sh); \
	cp .libs/libev.a ../; \
	cp ev.h ../
	@echo "[Done building libev]"